### ISSUE TITLE
ssh command does not get invoked in the shell

### ISSUE THREAD

**Issue by pthieu** [Webdown404/ssh-manager#1]
Reproduction steps:

1. add project using `ssh-manager add`
2. follow prompts and fill in information
3. invoke `ssh-manager connect`
4. select project using arrow keys, press enter to select
5. CLI exits after printing out the ssh command, doesn't seem to actually invoke it

Expected:
SSH command is invoked and I log into the server

`README.md` says:
>With it, you can create / modify / delete an SSH project configuration and **start an SSH connection**

OS: `macOS 10.12.5`

**Comment by Webdown404** [comment]
yes you’re wright! It’s a work in progress : i’m working on it to replace the string return by a SSH child process. I will implement it (with unit testing) for the v1.0.0

**Comment by pthieu** [comment]
NP. I was actually going to implement an ssh manager of my own, but I guess I can make PRs to this repo

**Comment by Webdown404** [comment]
Cool^^ i will take a look to review / merge it!

**Comment by Webdown404** [comment]
Hi, i've finished the wip. You can now enjoy an ssh connection with child process!

**Comment by pthieu** [comment]
@Webdown404 thanks!
